name: Wake up App

on:
  schedule:
    # Dit triggert om 06:00, 12:00 en 18:00 Amsterdamse tijd (Wintertijd / UTC+1)
    - cron: '0 5,11,17 * * *'
  workflow_dispatch:    # <--- DIT VOEGT DE TEST-KNOP TOE

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: curl -I "https://theunissen.streamlit.app/?wake=true"
